name: 'vk-notify'
description: 'Simple notifications to your VK conversation/private chat about happened actions in your repo'
author: 'YmerDev/AGG'
inputs:
  botToken:
    description: 'The Telegram Bot token'
    required: true
  chatId:
    description: 'The target to which the message will be sent, can be a Telegram Channel or Group'
    required: true
  jobStatus:
    description: 'The current status of the job: job.status'
    default: 'success'
    required: false
  message:
      description: 'Custom message if you need'
      default: ''
      required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
